import { Component, computed, input, signal } from '@angular/core';
import { Product } from '../../models/products';
import { ProductCard } from '../../components/product-card/product-card';
import { MatSidenavContainer, MatSidenavContent, MatSidenav } from '@angular/material/sidenav';
import { MatNavList, MatListItem, MatListItemTitle } from '@angular/material/list';
import { RouterLink } from "@angular/router";
import { TitleCasePipe } from '@angular/common';

@Component({
  selector: 'app-products-grid',
  imports: [ProductCard, MatSidenavContainer, MatSidenavContent, MatSidenav, MatNavList, MatListItem, MatListItemTitle, RouterLink, TitleCasePipe],
  templateUrl: './products-grid.html',
  styleUrl: './products-grid.scss',
})
export default class ProductsGrid {

  category = input<string>('all');

  products = signal<Product[]>([
    // Electronics
    {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    description: "Noise-cancelling over-ear headphones.",
    price: 89.99,
    imageUrl: "/product_images/product_1.png",
    rating: 4.5,
    reviewCount: 120,
    inStock: true,
    category: "Electronics",
  },
  {
    id: "2",
    name: "5G Android Smartphone",
    description: "High-performance smartphone with AMOLED display.",
    price: 699.99,
    imageUrl: "/product_images/product_2.png",
    rating: 4.7,
    reviewCount: 340,
    inStock: true,
    category: "Electronics",
  },
  {
    id: "3",
    name: "RGB Gaming Mouse",
    description: "High precision gaming mouse with customizable RGB.",
    price: 49.99,
    imageUrl: "/product_images/product_3.png",
    rating: 4.3,
    reviewCount: 89,
    inStock: true,
    category: "Electronics",
  },
  {
    id: "4",
    name: "Mechanical Gaming Keyboard",
    description: "Tactile keys with RGB backlighting.",
    price: 109.99,
    imageUrl: "/product_images/product_4.png",
    rating: 4.6,
    reviewCount: 210,
    inStock: true,
    category: "Electronics",
  },
  {
    id: "5",
    name: "Smart Fitness Watch",
    description: "Track health, steps, and notifications.",
    price: 149.99,
    imageUrl: "/product_images/product_5.png",
    rating: 4.5,
    reviewCount: 310,
    inStock: true,
    category: "Electronics",
  },
  {
    id: "6",
    name: "14-inch Ultrabook Laptop",
    description: "Lightweight laptop with long battery life.",
    price: 899.99,
    imageUrl: "/product_images/product_6.png",
    rating: 4.4,
    reviewCount: 180,
    inStock: false,
    category: "Electronics",
  },
  {
    id: "7",
    name: "10-inch Android Tablet",
    description: "Portable tablet with HD display.",
    price: 299.99,
    imageUrl: "/product_images/product_7.png",
    rating: 4.2,
    reviewCount: 140,
    inStock: true,
    category: "Electronics",
  },
  {
    id: "8",
    name: "Portable Bluetooth Speaker",
    description: "Deep bass speaker with long battery life.",
    price: 59.99,
    imageUrl: "/product_images/product_8.png",
    rating: 4.6,
    reviewCount: 220,
    inStock: true,
    category: "Electronics",
  },
  {
    id: "9",
    name: "1TB External Hard Drive",
    description: "Portable storage with fast transfer speeds.",
    price: 79.99,
    imageUrl: "/product_images/product_9.png",
    rating: 4.4,
    reviewCount: 160,
    inStock: true,
    category: "Electronics",
  },
  {
    id: "10",
    name: "Full HD Webcam",
    description: "1080p webcam for streaming and meetings.",
    price: 39.99,
    imageUrl: "/product_images/product_10.png",
    rating: 4.1,
    reviewCount: 95,
    inStock: true,
    category: "Electronics",
  },

  // Clothing (10)
  {
    id: "11",
    name: "Men's Cotton T-Shirt",
    description: "Soft and breathable everyday wear.",
    price: 19.99,
    imageUrl: "/product_images/product_11.png",
    rating: 4.2,
    reviewCount: 65,
    inStock: true,
    category: "Clothing",
  },
  {
    id: "12",
    name: "Women's Denim Jacket",
    description: "Classic denim jacket for all seasons.",
    price: 59.99,
    imageUrl: "/product_images/product_12.png",
    rating: 4.6,
    reviewCount: 150,
    inStock: false,
    category: "Clothing",
  },
  {
    id: "13",
    name: "Running Sports Shoes",
    description: "Lightweight shoes with breathable mesh.",
    price: 79.99,
    imageUrl: "/product_images/product_13.png",
    rating: 4.4,
    reviewCount: 200,
    inStock: true,
    category: "Clothing",
  },
  {
    id: "14",
    name: "Fleece Hoodie",
    description: "Warm hoodie for winter comfort.",
    price: 39.99,
    imageUrl: "/product_images/product_14.png",
    rating: 4.5,
    reviewCount: 130,
    inStock: true,
    category: "Clothing",
  },
  {
    id: "15",
    name: "Slim Fit Jeans",
    description: "Stylish denim jeans with stretch fit.",
    price: 49.99,
    imageUrl: "/product_images/product_15.png",
    rating: 4.3,
    reviewCount: 170,
    inStock: true,
    category: "Clothing",
  },
  {
    id: "16",
    name: "Casual Sneakers",
    description: "Comfortable sneakers for daily wear.",
    price: 69.99,
    imageUrl: "/product_images/product_16.png",
    rating: 4.4,
    reviewCount: 190,
    inStock: true,
    category: "Clothing",
  },
  {
    id: "17",
    name: "Formal Office Shirt",
    description: "Perfect shirt for professional wear.",
    price: 34.99,
    imageUrl: "/product_images/product_17.png",
    rating: 4.2,
    reviewCount: 85,
    inStock: true,
    category: "Clothing",
  },
  {
    id: "18",
    name: "Summer Shorts",
    description: "Lightweight shorts for hot weather.",
    price: 24.99,
    imageUrl: "/product_images/product_18.png",
    rating: 4.1,
    reviewCount: 70,
    inStock: true,
    category: "Clothing",
  },
  {
    id: "19",
    name: "Baseball Cap",
    description: "Adjustable cap with breathable fabric.",
    price: 14.99,
    imageUrl: "/product_images/product_19.png",
    rating: 4.0,
    reviewCount: 55,
    inStock: true,
    category: "Clothing",
  },
  {
    id: "20",
    name: "Cotton Socks Pack",
    description: "Pack of 5 soft cotton socks.",
    price: 12.99,
    imageUrl: "/product_images/product_20.png",
    rating: 4.3,
    reviewCount: 100,
    inStock: true,
    category: "Clothing",
  },

  // Home (10)
  {
    id: "21",
    name: "Wooden Coffee Table",
    description: "Modern table for living room decor.",
    price: 129.99,
    imageUrl: "/product_images/product_21.png",
    rating: 4.1,
    reviewCount: 45,
    inStock: true,
    category: "Home",
  },
  {
    id: "22",
    name: "LED Desk Lamp",
    description: "Adjustable brightness desk lamp.",
    price: 29.99,
    imageUrl: "/product_images/product_22.png",
    rating: 4.5,
    reviewCount: 78,
    inStock: true,
    category: "Home",
  },
  {
    id: "23",
    name: "Kitchen Blender",
    description: "High-speed blender for smoothies.",
    price: 99.99,
    imageUrl: "/product_images/product_23.png",
    rating: 4.3,
    reviewCount: 110,
    inStock: false,
    category: "Home",
  },
  {
    id: "24",
    name: "Minimal Wall Clock",
    description: "Elegant wall clock for home decor.",
    price: 19.99,
    imageUrl: "/product_images/product_24.png",
    rating: 4.2,
    reviewCount: 60,
    inStock: true,
    category: "Home",
  },
  {
    id: "25",
    name: "Decorative Sofa Cushion",
    description: "Soft cushion with stylish design.",
    price: 15.99,
    imageUrl: "/product_images/product_25.png",
    rating: 4.4,
    reviewCount: 90,
    inStock: true,
    category: "Home",
  },
  {
    id: "26",
    name: "4-Tier Bookshelf",
    description: "Spacious wooden storage shelf.",
    price: 149.99,
    imageUrl: "/product_images/product_26.png",
    rating: 4.3,
    reviewCount: 75,
    inStock: true,
    category: "Home",
  },
  {
    id: "27",
    name: "King Size Bed Sheet",
    description: "Soft cotton bedsheet set.",
    price: 39.99,
    imageUrl: "/product_images/product_27.png",
    rating: 4.5,
    reviewCount: 140,
    inStock: true,
    category: "Home",
  },
  {
    id: "28",
    name: "Blackout Curtains",
    description: "Light-blocking curtains for bedrooms.",
    price: 44.99,
    imageUrl: "/product_images/product_28.png",
    rating: 4.2,
    reviewCount: 85,
    inStock: true,
    category: "Home",
  },
  {
    id: "29",
    name: "Dining Table Set",
    description: "4-seater wooden dining set.",
    price: 399.99,
    imageUrl: "/product_images/product_29.png",
    rating: 4.4,
    reviewCount: 50,
    inStock: false,
    category: "Home",
  },
  {
    id: "30",
    name: "Standing Floor Lamp",
    description: "Elegant lamp for living spaces.",
    price: 59.99,
    imageUrl: "/product_images/product_30.png",
    rating: 4.3,
    reviewCount: 95,
    inStock: true,
    category: "Home",
  },

  // Books (10)
  {
    id: "31",
    name: "Mystery Thriller Novel",
    description: "Suspense-filled story with twists.",
    price: 14.99,
    imageUrl: "/product_images/product_31.png",
    rating: 4.8,
    reviewCount: 210,
    inStock: true,
    category: "Books",
  },
  {
    id: "32",
    name: "Science Fiction Adventure",
    description: "Journey through futuristic worlds.",
    price: 18.99,
    imageUrl: "/product_images/product_32.png",
    rating: 4.6,
    reviewCount: 175,
    inStock: true,
    category: "Books",
  },
  {
    id: "33",
    name: "Self Improvement Guide",
    description: "Boost productivity and mindset.",
    price: 12.99,
    imageUrl: "/product_images/product_33.png",
    rating: 4.2,
    reviewCount: 95,
    inStock: true,
    category: "Books",
  },
  {
    id: "34",
    name: "World Cuisine Cookbook",
    description: "Recipes from around the globe.",
    price: 22.99,
    imageUrl: "/product_images/product_34.png",
    rating: 4.7,
    reviewCount: 125,
    inStock: true,
    category: "Books",
  },
  {
    id: "35",
    name: "History of Civilizations",
    description: "Explore ancient to modern history.",
    price: 24.99,
    imageUrl: "/product_images/product_35.png",
    rating: 4.3,
    reviewCount: 80,
    inStock: true,
    category: "Books",
  },
  {
    id: "36",
    name: "Inspirational Biography",
    description: "Story of a remarkable life journey.",
    price: 19.99,
    imageUrl: "/product_images/product_36.png",
    rating: 4.5,
    reviewCount: 140,
    inStock: true,
    category: "Books",
  },
  {
    id: "37",
    name: "Fantasy Adventure Novel",
    description: "Magic, dragons, and epic quests.",
    price: 17.99,
    imageUrl: "/product_images/product_37.png",
    rating: 4.6,
    reviewCount: 160,
    inStock: true,
    category: "Books",
  },
  {
    id: "38",
    name: "Web Development Guide",
    description: "Learn modern full-stack development.",
    price: 29.99,
    imageUrl: "/product_images/product_38.png",
    rating: 4.7,
    reviewCount: 220,
    inStock: true,
    category: "Books",
  },
  {
    id: "39",
    name: "Poetry Collection",
    description: "A collection of modern poems.",
    price: 11.99,
    imageUrl: "/product_images/product_39.png",
    rating: 4.1,
    reviewCount: 60,
    inStock: true,
    category: "Books",
  },
  {
    id: "40",
    name: "Travel Explorer Guide",
    description: "Discover top travel destinations.",
    price: 21.99,
    imageUrl: "/product_images/product_40.png",
    rating: 4.4,
    reviewCount: 90,
    inStock: true,
    category: "Books",
  },

  // Fitness (10)
  {
    id: "41",
    name: "Premium Yoga Mat",
    description: "Non-slip mat for yoga and workouts.",
    price: 24.99,
    imageUrl: "/product_images/product_41.png",
    rating: 4.5,
    reviewCount: 130,
    inStock: true,
    category: "Fitness",
  },
  {
    id: "42",
    name: "Adjustable Dumbbell Set",
    description: "Perfect for home strength training.",
    price: 59.99,
    imageUrl: "/product_images/product_42.png",
    rating: 4.7,
    reviewCount: 220,
    inStock: true,
    category: "Fitness",
  },
  {
    id: "43",
    name: "Foldable Treadmill",
    description: "Compact treadmill for home workouts.",
    price: 499.99,
    imageUrl: "/product_images/product_43.png",
    rating: 4.4,
    reviewCount: 80,
    inStock: false,
    category: "Fitness",
  },
  {
    id: "44",
    name: "Resistance Bands Kit",
    description: "Full-body workout bands set.",
    price: 19.99,
    imageUrl: "/product_images/product_44.png",
    rating: 4.4,
    reviewCount: 90,
    inStock: true,
    category: "Fitness",
  },
  {
    id: "45",
    name: "Indoor Exercise Bike",
    description: "Smooth and quiet cycling experience.",
    price: 299.99,
    imageUrl: "/product_images/product_45.png",
    rating: 4.3,
    reviewCount: 110,
    inStock: true,
    category: "Fitness",
  },
  {
    id: "46",
    name: "Skipping Rope",
    description: "Adjustable rope for cardio workouts.",
    price: 9.99,
    imageUrl: "/product_images/product_46.png",
    rating: 4.2,
    reviewCount: 70,
    inStock: true,
    category: "Fitness",
  },
  {
    id: "47",
    name: "Cast Iron Kettlebell",
    description: "Durable kettlebell for strength training.",
    price: 34.99,
    imageUrl: "/product_images/product_47.png",
    rating: 4.5,
    reviewCount: 85,
    inStock: true,
    category: "Fitness",
  },
  {
    id: "48",
    name: "Doorway Pull-up Bar",
    description: "Easy install bar for home workouts.",
    price: 39.99,
    imageUrl: "/product_images/product_48.png",
    rating: 4.3,
    reviewCount: 95,
    inStock: true,
    category: "Fitness",
  },
  {
    id: "49",
    name: "Foam Roller",
    description: "Muscle recovery and massage tool.",
    price: 21.99,
    imageUrl: "/product_images/product_49.png",
    rating: 4.4,
    reviewCount: 75,
    inStock: true,
    category: "Fitness",
  },
  {
    id: "50",
    name: "Workout Gym Gloves",
    description: "Protective gloves for lifting.",
    price: 14.99,
    imageUrl: "/product_images/product_50.png",
    rating: 4.2,
    reviewCount: 60,
    inStock: true,
    category: "Fitness",
  },
]);

  filteredProducts = computed(() => {
    if (this.category() === 'all') return this.products();

    return this.products().filter(
      p => p.category.toLowerCase() === this.category().toLowerCase()
    );
  });

  categories = signal<string[]>(['all',   "electronics", "clothing", "home", "books", "fitness"]);
}